name: Backend Tests

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write
  issues: write
  repository-projects: read

jobs:
  backend-tests:
    name: Backend Tests (Pytest)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests
        run: |
          cd backend
          pytest

      - name: Run tests with coverage
        run: |
          cd backend
          pytest --cov=. --cov-report=xml --cov-report=html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: backend/
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/htmlcov/
          retention-days: 7

      - name: Generate test summary
        if: always()
        run: |
          echo "## Backend Test Results" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Pytest tests completed" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 Coverage report generated" >> $GITHUB_STEP_SUMMARY
          if [ -f "backend/htmlcov/index.html" ]; then
            echo "- 📈 Coverage details available in artifacts" >> $GITHUB_STEP_SUMMARY
          fi